apiVersion: 1

datasources:
  - name: DS_INFLUXDB
    isDefault: true
    type: influxdb
    access: proxy
    database: ${INFLUXDB_DB}
    url: http://${PROJ_NAME}-influxdb:8086
    jsonData:
      httpMode: GET