{
 "title": "VMware vSphere  - Hosts",
 "description": "VMware vSphere Dashboard using the new Telegraf plugin (Grafana 7)",
 "tags": [
  "VMware",
  "vSphere Hosts",
  "vSphere Telegraf"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": "select DISTINCT(\"vcenter\") from (select \"usage_average\",\"vcenter\" from \"vsphere_host_cpu\" WHERE $timeFilter)"
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": "select DISTINCT(\"clustername\") from (select \"usage_average\",\"clustername\" from \"vsphere_host_cpu\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": "select DISTINCT(\"esxhostname\") from (select \"usage_average\",\"esxhostname\" from \"vsphere_host_cpu\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "select DISTINCT(\"dsname\") from (select \"used_latest\",\"dsname\" from \"vsphere_datastore_disk\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   },
   {
    "name": "esxiarm",
    "label": "ESXi ARM Server",
    "query": "SHOW TAG VALUES FROM vsphere_esxi_arm WITH KEY=hostname"
   }
  ]
 },
 "panels": [
  { "title": "$esxi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "esxi" },
  {
   "title": "ESXi VM Quick Overview",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_sys",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "CPU Usage MHz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "RAM Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "query": "SELECT last(\"totalCapacity_average\") * (last(\"usage_average\")) / 100 * 1024 FROM \"vsphere_host_mem\" WHERE (\"esxhostname\" =~ /^$esxi$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "CPU Usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "RAM Usage %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization Avg %",
   "type": "graph",
   "description": "CPU usage as a percentage during the interval.",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization %" }
   ],
   "targets": [
    {
     "alias": "CPU usage % $tag_cpu",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "RAM Usage in %" }
   ],
   "targets": [
    {
     "alias": "RAM usage %",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Ready in miliseconds",
   "type": "graph",
   "description": "Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "CPU Ready",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "ready_summation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "Network utilization (combined transmit-rates and receive-rates) during the interval.",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "KBs", "label": "Network Usage" }
   ],
   "targets": [
    {
     "alias": "$tag_interface bytesRx",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "bytesRx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "$tag_interface bytesTx",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "bytesTx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Latency",
   "type": "graph",
   "description": "The average time a read, or write, from the virtual disk takes.",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "KBps" }
   ],
   "targets": [
    {
     "alias": "Write - $tag_disk",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_disk",
     "select": [
      [
       { "params": [ "totalReadLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "Read - $tag_disk",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_disk",
     "select": [
      [
       { "params": [ "totalWriteLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Adapter IOPS",
   "type": "graph",
   "description": "The average time a read, or write, from the datastore takes.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    {
     "alias": "$tag_adapter Read",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "adapter" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "select": [
      [
       { "params": [ "numberReadAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "$tag_adapter Write",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "adapter" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "select": [
      [
       { "params": [ "numberWriteAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "ARM - $esxiarm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "repeat": "esxiarm",
   "collapsed": true,
   "panels": [
    {
     "title": "ESXi VM Quick Overview",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Uptime",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_sys",
       "select": [
        [
         { "params": [ "uptime_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "CPU Usage MHz",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usagemhz_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "RAM Usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "query": "SELECT last(\"totalCapacity_average\") * (last(\"usage_average\")) / 100 * 1024 FROM \"vsphere_host_mem\" WHERE (\"esxhostname\" =~ /^$esxi$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "active_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "CPU Usage %",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "RAM Usage %",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "CPU Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_esxi_arm",
       "select": [
        [
         { "params": [ "boardtemp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$esxiarm$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Utilization Avg %",
     "type": "graph",
     "description": "CPU usage as a percentage during the interval.",
     "gridPos": { "h": 7, "w": 6, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "percent", "label": "CPU Utilization %" }
     ],
     "targets": [
      {
       "alias": "CPU usage % $tag_cpu",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "percent", "label": "RAM Usage in %" }
     ],
     "targets": [
      {
       "alias": "RAM usage %",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Temperature",
     "type": "graph",
     "description": "CPU Temperature",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius", "label": "CPU Temperature in Celsius" }
     ],
     "targets": [
      {
       "alias": "CPU Temperature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_esxi_arm",
       "select": [
        [
         { "params": [ "boardtemp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$esxiarm$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "graph",
     "description": "Network utilization (combined transmit-rates and receive-rates) during the interval.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "KBs", "label": "Network Usage" }
     ],
     "targets": [
      {
       "alias": "$tag_interface bytesRx",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_net",
       "select": [
        [
         { "params": [ "bytesRx_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "$tag_interface bytesTx",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_net",
       "select": [
        [
         { "params": [ "bytesTx_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Disk Latency",
     "type": "graph",
     "description": "The average time a read, or write, from the virtual disk takes.",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "none", "label": "KBps" }
     ],
     "targets": [
      {
       "alias": "Write - $tag_disk",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "disk" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_disk",
       "select": [
        [
         { "params": [ "totalReadLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "Read - $tag_disk",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "disk" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_disk",
       "select": [
        [
         { "params": [ "totalWriteLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "Storage Adapter IOPS",
     "type": "graph",
     "description": "The average time a read, or write, from the datastore takes.",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "IOPS" }
     ],
     "targets": [
      {
       "alias": "$tag_adapter Read",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "adapter" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_storageAdapter",
       "select": [
        [
         { "params": [ "numberReadAveraged_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      },
      {
       "alias": "$tag_adapter Write",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "adapter" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_storageAdapter",
       "select": [
        [
         { "params": [ "numberWriteAveraged_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Ready in miliseconds",
     "type": "graph",
     "description": "Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval.",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
     "yaxes": [
      { "format": "none", "label": "ms" }
     ],
     "targets": [
      {
       "alias": "CPU Ready",
       "groupBy": [
        { "params": [ "20s" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "ready_summation" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}