{
 "title": "VMware vSphere  - VMs",
 "description": "VMware vSphere Dashboard using the new Telegraf plugin (Grafana 7)",
 "tags": [
  "VMware",
  "vSphere VM",
  "vSphere Telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": "select DISTINCT(\"vcenter\") from (select \"usage_average\",\"vcenter\" from \"vsphere_host_cpu\" WHERE $timeFilter)"
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": "select DISTINCT(\"clustername\") from (select \"usage_average\",\"clustername\" from \"vsphere_host_cpu\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": "select DISTINCT(\"esxhostname\") from (select \"usage_average\",\"esxhostname\" from \"vsphere_host_cpu\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "select DISTINCT(\"dsname\") from (select \"used_latest\",\"dsname\" from \"vsphere_datastore_disk\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   },
   {
    "name": "virtualmachine",
    "label": "VM",
    "query": "select DISTINCT(\"vmname\") from (select \"ready_summation\",\"vmname\" from \"vsphere_vm_cpu\" WHERE $timeFilter AND \"vcenter\" =~ /$vcenter/)"
   }
  ]
 },
 "panels": [
  { "title": "$virtualmachine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "virtualmachine" },
  {
   "title": "VM Quick Overview",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_sys",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "CPU Usage MHz",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "RAM Usage",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "CPU Usage %",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "RAM Usage %",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage in %",
   "type": "graph",
   "description": "CPU usage as a percentage during the interval.",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilization %" }
   ],
   "targets": [
    {
     "alias": "CPU usage %",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "CPU Ready %",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "readiness_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "Amount of guest physical memory that is being actively read or written by guest. Activeness is estimated by ESXi.",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "RAM Usage in %" }
   ],
   "targets": [
    {
     "alias": "RAM usage %",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Ready in miliseconds",
   "type": "graph",
   "description": "Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "Core $tag_cpu",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "ready_summation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "Network utilization (combined transmit-rates and receive-rates) during the interval.",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "KBs", "label": "Network Usage" }
   ],
   "targets": [
    {
     "alias": "$tag_interface bytesRx",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_net",
     "select": [
      [
       { "params": [ "bytesRx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "$tag_interface bytesTx",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_net",
     "select": [
      [
       { "params": [ "bytesTx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Latency",
   "type": "graph",
   "description": "The average time a read, or write, from the virtual disk takes.",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "Write - $tag_disk",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "totalWriteLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "Read - $tag_disk",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "totalReadLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Adapter Latency",
   "type": "graph",
   "description": "The average time a read, or write, from the datastore takes.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "ReadAverage $tag_disk",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "totalReadLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "WriteAverage $tag_disk",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "totalWriteLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  }
 ]
}